# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - app_dir: kubeflow/chainer-operator/test/workflows
  # this super-short names are required so that identity lengths will be shorter than 64
    component: e2e
    name: chr
    job_types:
      - presubmit
    params:
      registry: "gcr.io/kubeflow-ci"
  - app_dir: kubeflow/chainer-operator/test/workflows
    component: rl
  # this super-short names are required so that identity lengths will be shorter than 64
    name: chr
    job_types:
      - postsubmit
    params:
      registry: "gcr.io/kubeflow-images-public"
